# Generated by Django 5.2.17 on 2026-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='身分證（選填）'),
        ),
        migrations.AlterField(
            model_name='child',
            name='tracking_status',
            field=models.CharField(blank=True, choices=[('', '請選擇'), ('一般', '一般'), ('氣喘追蹤', '氣喘追蹤'), ('早療追蹤', '早療追蹤'), ('其他', '其他')], db_index=True, max_length=50, verbose_name='追蹤狀態'),
        ),
    ]
