# Generated by Django 5.2.17 on 2026-09-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_seed_tiers_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityrule',
            name='condition_json',
            field=models.JSONField(blank=True, default=dict, help_text='Builder 以表單設定適用起訖日、填答頻率與建議填答時點。', verbose_name='其他條件'),
        ),
    ]
